# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 540fdd173487fa68ead327f42e490b5d670db9d82af29cea36937f68958740def46ca6057bd3998fae0be6d6084778f909a5492972318d377ba0c8f1695cd626

test:
  secret_key_base: cbd98bdaf6f053e2cdc307e99fc49ab60e85f83ecc8b8f70dd79a1f8dc415fbe526bc00ac156dd6b6594be2d0981a6b82d38cf060b3f8fa350de39123af3282c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
